### ISSUE TITLE
Update metadata of raw datasets

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digipipe#104]
As in #43, create metadata for new bunch of [raw datasets](https://github.com/rl-institut-private/digipipe/tree/dev/digipipe/store/raw):
- `ageb_energy_balance`
- `ba_employment`
- `bmwk_long_term_scenarios`
- `dbfz_biomass_heat_capacities` (as soon as #160 is merged)
- `demandregio`
- `dwd_temperature`
- `emissions` (the data you and @dvdstrzl added)
- `eurostat_lau`
- `regiostat`
- `renewables.ninja_feedin`
- `rli_pv_wfr`
- `rpg_abw_pv_roof_potential`
- `rpg_abw_regional_plan`
- `seenergies_peta5`
- `stala_st_energy`
- `technology_data`

Like before, find link(s) in the respective `metadata.json` and more information in the `dataset.md`. If helpful, the raw files are located on the [Wolke](https://wolke.rl-institut.de/f/160572).

**Comment by aaronschilling** [comment]
updated metadata in [Update_metadata_of_raw_datasets_#104](https://github.com/rl-institut/digipipe/tree/Update_metadata_of_raw_datasets_%23104)
missing:
- dbfz_biomass_heat_capacities

technology_data done in [updating_technology_data_dataset.md](https://github.com/rl-institut/digipipe/tree/updating_technology_data_dataset.md)
