### ISSUE TITLE
Add capacities for CHPs

### ISSUE THREAD

**Issue by henhuy** [rl-institut/digipipe#119]
I need capacities for all components in ES either from sliders or from config (CSV/JSON/datapackage).
Right now, I can not see options in app settings or settings excel for following components:
- ABW-biogas-bpchp_central
- ABW-biogas-bpchp_decentral
- ABW-wood-extchp_central
- ABW-wood-extchp_decentral
- ABW-ch4-bpchp_central
- ABW-ch4-bpchp_decentral"
- ABW-ch4-extchp_centra
- ABW-ch4-extchp_decentral
- ABW-ch4-gt
- ABW-biogas-biogas_upgrading_plant
- ABW-biomass-biogas_plant

Maybe more...
Somehow I need those capacities. Thx

**Comment by nesnoj** [comment]
This can be closed now, right @henhuy ?

**Comment by henhuy** [comment]
I think so - as they are calculated in digiplan
