### ISSUE TITLE
Update ASHP and GSHP split

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digipipe#164]
The split between ASHP and GSHP is currently set to 50:50 which is a dummy value.

For 2045, please
- use realistic value and adjust [here](https://github.com/rl-institut-private/digipipe/blob/bb8118cc3c480d3873e95aa08d5a7ca0e8a51d83/digipipe/store/datasets/heatpump_cop/config.yml#L9-L10)
- Update the [docs](https://github.com/rl-institut-private/digipipe/blob/bb8118cc3c480d3873e95aa08d5a7ca0e8a51d83/digipipe/store/datasets/heatpump_cop/dataset.md#L25-L27) accordingly

@aaronschilling We talked about this some time ago, maybe you can do it?

**Comment by aaronschilling** [comment]
Die Absatzzahlen aus der [Branchenstudie des Bundesverband Wärmepumpe (BWP) e. V.](https://www.waermepumpe.de/fileadmin/user_upload/waermepumpe/05_Presse/01_Pressemitteilungen/BWP_Branchenstudie_2023_DRUCK.pdf) von 2022 hat einen Split von 87:13 im Jahre 2022. Über die letzten 10 Jahre in etwa ein 80:20. Da die Entwicklung stark zur Lufwärmepumpe geht, wurde in der cost_effiency Tabelle der Wert für 2045 mit den Absatzzahlen von 2022 abgeschätzt.
Ich würde vorschlagen, diesen Split auch hier zu nutzen.

**Comment by nesnoj** [comment]
> 

Thx! Yes, please adjust

> Die Absatzzahlen aus der [Branchenstudie des Bundesverband Wärmepumpe (BWP) e. V.](https://www.waermepumpe.de/fileadmin/user_upload/waermepumpe/05_Presse/01_Pressemitteilungen/BWP_Branchenstudie_2023_DRUCK.pdf) von 2022 hat einen Split von 87:13 im Jahre 2022. Über die letzten 10 Jahre in etwa ein 80:20. Da die Entwicklung stark zur Lufwärmepumpe geht, wurde in der cost_effiency Tabelle der Wert für 2045 mit den Absatzzahlen von 2022 abgeschätzt. Ich würde vorschlagen, diesen Split auch hier zu nutzen. Wenn das so ok ist, kann ich das schnell einpflegen.

Thanks, I already started to fix ;)

**Comment by aaronschilling** [comment]
so schnell. Schön :D
