### ISSUE TITLE
Add dataset: efficiencies and costs of components, carrier emissions

### ISSUE THREAD

**Issue by MaGering** [rl-institut/digipipe#38]
The following data needs to be gathered:

- capacity_cost_overnight
- condensing_efficiency
- efficiency
- electric_efficiency
- expandable
- fixom_cost
- input_parameters
- lifetime
- loss_rate
- marginal_cost
- storage_capacity_cost_overnight
- storage_fixom_cost
- thermal_efficiency
- wacc

 It is corresponding data of these components:

- boiler_large
- boiler_small
- bpchp_small
- extchp_large
- gt
- heatpump_large
- heatpump_small
- large_scale_battery
- bev_charging
- pth_small
- pth_large
- oven (wood)
- oven (lignite)
- fermenter
- storage (heat_central)
- storage (heat_decentral)
- onshore
- pv_ground
- pv_rooftop
- thermalcollector

Also, add specific emissions for carriers

**Comment by nesnoj** [comment]
Done
