### ISSUE TITLE
Centralize region configuration

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digipipe#44]
The region of interest (the data is generated for) is defined decentrally: some configs hold NUTS3 codes ([example](https://github.com/rl-institut/digipipe/blob/06b331b9b9a7d02c46ae123d00445c37a037db88/digipipe/store/datasets/bkg_vg250_muns_region/config.yml#L13)) names of the districts ([example](https://github.com/rl-institut/digipipe/blob/06b331b9b9a7d02c46ae123d00445c37a037db88/digipipe/store/datasets/bnetza_mastr_biomass_region/config.yml#L32)).

- [x] Define NUTS3 codes for region of interest in central config file
- [x] Adapt existing datasets to use the definition

Test with ABW region, then NUTS3 of the EPP project. It involves:
- `DE409` (Märkisch-Oderland)
- `DE40C` (Oder-Spree)

Related: #190

**Comment by dvdstrzl** [comment]
- [x] succesfully tested with ABW

**Comment by dvdstrzl** [comment]
Test with `DE409` (Märkisch-Oderland) and `DE40C` (Oder-Spree):  Pipeline fails at some point (Step 72 of 171) 

Unfortunately I can't identifiy where/why the error happens (log too unspecific)

**Comment by dvdstrzl** [comment]
Tested with `DE409` (Märkisch-Oderland) and `DE40C` (Oder-Spree): Pipeline fails at some point (~ Step 70 of 171)

Unfortunately I can't identifiy where/why the error happens (log too unspecific)
